### PR TITLE
Add line highlighting support

### PR DESCRIPTION
**Pull request by litao91**
Extend the fenced code highlighting syntax

Use the syntax like

~~~
```cpp{1,2,3}
```
~~~

To highlight the lines of 1, 2 and 3.

### CODE REVIEW

**Comment by yuin** [comment]
Good PR.
Attribute syntax like `{lines=[1,2,3]}` has more extensibility and consistency with other syntax than current syntax(`{1,2,3}`).
How you do you feel about it?

I'm now re-writing attribute parsing. New attribute parsing function has already been commited as [attribute.go](https://github.com/yuin/goldmark/blob/master/parser/attribute.go). It has not been tested
though, works in common cases.

**Comment by litao91** [comment]
HI @yuin 
I've modified to use attribute. Instead of `lines`, I'm using the attribute name as `hl_lines` to be more informative. 

Thanks

**Comment by yuin** [comment]
Great.

Ideally, attributes should be parsed in parsing phase but currently fenced code blocks does not support attributes. In the future, fenced code may have attributes in parsing phase. So it may be better for future compatibility to check if  attributes existence with [`ast.Node.GetAttribute`](https://github.com/yuin/goldmark/blob/master/ast/ast.go#L155) before trying to parse attributes in renderers .

It seems `hl_lines` can has single range of the lines.  [Hugo](https://gohugo.io/content-management/syntax-highlighting/) and [Pygments](http://pygments.org/docs/formatters/) can have multiple ranges of the lines.  It would be great if can specify lines like `hl_lines=[3, "11-15"]` .

**Comment by litao91** [comment]
@yuin 
Hi yuin, now the attributes will be checked. And I add one more `style` attribute, now we may have syntax like 

~~~
```go{hl_lines=[1,2,"7-10"],style=monokai}
<your code>
```
~~~

Thanks

**Comment by yuin** [comment]
Hmm, `style` may conflict HTML style attribute if fenced codes may have attributes in parsing phase in the future.

~~~
```go {#id .my-class style="float:left"}

```
~~~
->
~~~
<pre class="my-class language-go" id="id" style="float:left"><code>
</code></pre>
~~~

name like `hl_style` or `data-hl-style`(and `data-hl-lines`) is more preferable for me.

~~~
```go {#id .my-class style="float:left" data-hl-style="monokai"}

```
~~~
->
~~~
<pre class="my-class" id="id" style="float:left" data-hl-style="monokai"><code>
</code></pre>
~~~

**Comment by litao91** [comment]
@yuin Okay, using `hl_style` now

**Comment by yuin** [comment]
@litao Good. I've merged this PR.

**Pull request merged**
